import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Header from '@/components/Header'
import Head from 'next/head';
import Section from '@/components/SectionA';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Excella Energy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Your Next.js App</title>
        <meta name="Excella Energy Services" content="Your app description" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Navbar/>
        <Header />
        <Section/>
        {children}
      </body>
    </html>
  )
}
